### ISSUE TITLE
use case: Using batarang to test a chrome extension

### ISSUE THREAD

**Issue by dcohenb** [angular/batarang#103]
Is there any way to make batarang work on a chrome extension developed on angular?
i.e https://developer.chrome.com/apps/angular_framework

**Comment by SomeKittens** [comment]
Yes!  Inspecting the background page of a Chrome extension includes all of the DevTools, including Batarang.

You can also open the DevTools for the DevTools by popping them out of Chrome and hitting the keyboard shortcut for opening the DevTools.  (And yes, I've used Batarang to debug Batarang).
