### ISSUE TITLE
Batarangathon 1

### ISSUE THREAD

**Issue by btford** [angular/batarang#108]
ping @aaronfrost

I thought we could keep meeting notes here. My goal for this first push is to better test and document Batarang so that it's easier for others to contribute.

- [x] Setup test coverage for Karma
- [ ] Continuous Integration via TravisCI or similar 
- [ ] Document how to build/test Batarang
- [x] Document Batarang internals
- [x] Add `inline.js` to Grunt
- [ ] Automate releases – Chrome web store API

**Comment by SomeKittens** [comment]
We have separate issues for the remaining tasks.

@iammerrick You're in luck!  Angular 2 has that.
