### ISSUE TITLE
Batarangathon 2 - Dependency Graph

### ISSUE THREAD

**Issue by aaronfrost** [angular/batarang#109]
- [ ] Add a search box that hides anything not connected to that dependency. 
- [ ] Top 10 dependencies by usage count

Huge dependency trees like the following are what we need to solve. They are unreadable: 
![018e03a5-060d-4ebe-9d92-af6a30350136](https://cloud.githubusercontent.com/assets/662832/2649732/0f243c52-bf67-11e3-9cd0-305df7812348.png)

**Comment by masonicGIT** [comment]
Would be great to simply make this resizable in the short term. I'm having the same issue as the poster

**Comment by SomeKittens** [comment]
@masonicGIT The dependency graph is not in the latest version of Batarang (`v0.10.1`).  Are you using Batarang Stable?  That extension is not affiliated with this project.

Closing this issue as our current version does not include a dependency graph.
