### ISSUE TITLE
watchFnToHumanReadableString: errors on undefined string

### ISSUE THREAD

**Issue by ajoslin** [angular/batarang#112]
https://github.com/angular/angularjs-batarang/blob/master/js/inject/debug.js#L714

Error if `fn` is undefined, while Angular is fine with fn being undefined.

**Comment by ardeearam** [comment]
+1 @fabiobiondi I lost one hour of my life as well. Just turned off the batarang, and all is well.

**Comment by SomeKittens** [comment]
@ardeearam This was closed over a year ago, are you sure you're on the latest version?

**Comment by dtruel** [comment]
I had this issue too - turning off batarang fixed it.  This was causing me the issue:

```javascript
var watchFnToHumanReadableString = function (fn) {
            if (fn.exp) {
              return fn.exp.trim();
            } else if (fn.name) {
              return fn.name.trim();
            } else {
              return fn.toString();
            }
          };
```

I am watching an object that looks like this `{name:1}` - which causes this thing to error out when it tries to run trim() on it.

**Comment by SomeKittens** [comment]
@dtruel What version of Batarang do you have?

**Comment by dtruel** [comment]
I was using 0.4.3.  Strangely enough, I reenabled it today and it started working.  I'm really not sure why.

**Comment by SomeKittens** [comment]
If you've got the "Stable" version, that's not official and isn't supported by this project.  Make sure you have the real one from here: https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk?hl=en
