### ISSUE TITLE
Is Batarang supposed to work with angular 1.3+?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [angular/batarang#131]
Because it seems that it doesn't.  I have chrome 36 on linux mint.  According to extensions Batarang is version 0.4.3.

With my working Angular app, I click on the AngularJS tab, check the enable box and my browser displays a blank page above the Batarang developer stuff.  Nothing anywhere to indicate I've got an Angular app loaded or running other than the network tab shows all the files loading properly.

It shows nothing different in Batarang's views than before I enabled it and my page is blank, nothing showing.

If I click again on enable my page and angular app loads perfectly normally as if the user has just clicked on refresh.

It's like Batarang's only purpose is to disable my app and then do nothing.

Also it seems a great many people on the web store are claiming it doesn't work for them either, perhaps because it doesn't work on the latest Angular 1.3?  The readme doesn't appear to contain any information that I can find about supported versions of anything relevant, perhaps that needs to be updated as well?

**Comment by gimzani** [comment]
Hey all:

If you're serving these pages from the file system, Batarang doesn't show the scopes.  I'm not sure why, but when I run it from a folder, I don't get scopes, but when I run it through IIS, node.js or Tomcat, it runs great.

Try that and see if it works for you.

**Comment by arminbw** [comment]
Hi!
I'm relatively new in the angular game, so please excuse my frivolity.
The current Batarang master build (v0.7.4) only gives me a blank page. No enable box. I don't even see the tabs. I'm using Chrome Version 39.0.2171.95 (64-bit) on OSX 10.10.1 and angular.js v1.3.8. I hope these problems can be resolved. Batarang is a great learning tool.

For the moment I reverted back to Batarang v0.4.3 (June 2013!) which more or less seems to work for me.

**Comment by demisx** [comment]
@arminbw It's supposed to, but it doesn't. Use http://ng-inspector.org/ instead.

**Comment by tehXor** [comment]
@btford instead of closing this topic you should remove the project from the store. In it's current state I'd say it's broken beyond repair and it's just normal that people react how they do (store reviews, comments here) when the can still download a project which is supposed to work but doesn't.

**Comment by dragosrususv** [comment]
@btford : same thought as @tehXor - it's fully broken. If you need help, just point us the issues you are having and we can do some PR's - but having a Chrome extension in the store in an unusable state is unacceptable.

**Comment by stevemao** [comment]
@WhatFreshHellIsThis You can send a PR to fix the issue

**Comment by jdruiter** [comment]
Check out version 5.0, its the latest one that worked for me
https://github.com/angular/angularjs-batarang/releases

**Comment by demisx** [comment]
@jdruiter Do you mean 0.5.0? If so, I believe there are issue with ng 1.3+

**Comment by jdruiter** [comment]
I found a better solution: 

AngularJS Batarang stable (its in the chrome play store)

Thanks to the developer probalbly for making it!

**Comment by dragosrususv** [comment]
@jdruiter : thanks a lot, that works!!! Finally!

**Comment by davidwparker** [comment]
As above, had to use AngularJS Batarang stable:
https://chrome.google.com/webstore/detail/angularjs-batarang-stable/niopocochgahfkiccpjmmpchncjoapek

Less than ideal, since the official one breaks all over on my bootstrapped app.

**Comment by dragosrususv** [comment]
@btford - there are tens of people who are posting confirmations of the fact the updates that were applied on official plugin broke everything - noone is considering fixing the official plugin?
