### ISSUE TITLE
feat: add ng-stats to batarang

### ISSUE THREAD

**Issue by kentcdodds** [angular/batarang#132]
I have a utility that I use to help with looking at performance in angular apps called [ng-stats](https://github.com/kentcdodds/ng-stats). Right now it just gives the watch count and the digest cycle length. What would you say about a pull request to include this information when batarang is enabled?

**Comment by SomeKittens** [comment]
I'll hack this out tonight.

**Comment by SomeKittens** [comment]
Ran into a few problems with the `angular-hint` suite, @btford said he's on it.

**Comment by SomeKittens** [comment]
Angular hint now emits events regarding profiling, Batarang just needs to display them.

**Comment by SomeKittens** [comment]
This was completed in f8359a9f410a173397f461a6ffc14c4b52ad2990
