### ISSUE TITLE
bug: HTML in model attribute is rendered

### ISSUE THREAD

**Issue by henrik** [angular/batarang#135]
This has some YouTube embed HTML:

![screenshot](http://cl.ly/image/0j270S3h2A1H/Image%202014-08-19%20at%203.59.49%20pm.png)

**Comment by SomeKittens** [comment]
Still an issue in latest
<img width="374" alt="screen shot 2015-11-12 at 1 07 47 pm" src="https://cloud.githubusercontent.com/assets/1616464/11131222/6a61e1b2-893e-11e5-8611-44285cfecd18.png">

**Comment by henrik** [comment]
@SomeKittens :tada: Awesome, good job!
