### ISSUE TITLE
One time bound expressions don't work with Batarang enabled in Chrome

### ISSUE THREAD

**Issue by demisx** [angular/batarang#140]
Any one time bound expression I define as `{{::someExp}}` still shows up in the `Watch Tree` and `Watch expressions`. Shouldn't it be removed once the stable value has been assigned?

**Comment by JerryBels** [comment]
Hey,

I still see one time bound expressions in the watchers list of Batarang. And, more importantly, when interacting with some elements to trigger a digest cycle, the time used by the watch increases as well ! Does that means one time bindings still have some relations with the digest cycle or is it a batarang issue ?

**Comment by SomeKittens** [comment]
@JerryBels You're using the "stable" version which is not supported nor connected to this project at all (nor actually stable).

**Comment by JerryBels** [comment]
@SomeKittens Oh, sorry ! I started by using the "regular" version, but it turned out it hasn't really a lot of info I could use... Thanks anyway.

**Comment by NamPNQ** [comment]
+1

**Comment by SomeKittens** [comment]
@NamPNQ GitHub added the ability to 👍 a message, please don't add useless comments

**Comment by NamPNQ** [comment]
@SomeKittens Sr, I don't see this feature in mobile

**Comment by marcoturi** [comment]
+1
