### ISSUE TITLE
feat: disable angular-hint

### ISSUE THREAD

**Issue by laurelnaiad** [angular/batarang#158]
If I'm being crazy, please let me know -- it happens. I think that maybe batarang just started invoking angular-hint on angular apps?

Is there any way to disable this? I want to keep batarang enabled, but angular-hint is cluttering the console, and most of it is documenting all of the style issues in dependencies over which I have "not so much" control...

**Comment by stanleyxu2005** [comment]
I'm wondering why batarang suggest rename `FooCtrl` to `FooController`. Any good reason for that?

**Comment by SomeKittens** [comment]
As recommended by the docs:

> SpicyController is just a plain JavaScript function. As an (optional) naming convention the name starts with capital letter and ends with "Controller".

https://docs.angularjs.org/guide/controller
