### ISSUE TITLE
Support disabling specific messages / types for angular hint

### ISSUE THREAD

**Issue by kentcdodds** [angular/batarang#159]
AFAIK this isn't yet possible with angular-hint yet, so this may just mean adding the ability of disabling angular-hint entirely for now, but I'm getting so many hints in my console that it's prohibitively excessive. I would also really like to specify custom hints (which I believe is also not possible with angular-hint yet). But as soon as possible, I'd like to be able to disable angular-hint in batarang.

It's incredibly overwhelming. When you're using a bunch of modules that don't follow what angular-hint says is the "best practice" and when you're controllers don't follow the "best practice" naming convention, the messages grow very quickly.

**Comment by stanleyxu2005** [comment]
+1 Ctrl is IMO okay. I'd kill this hint.
