### ISSUE TITLE
ux: Add arrow for expandable properties in models pane

### ISSUE THREAD

**Issue by kentcdodds** [angular/batarang#161]
If something expands, it would be nice to have an arrow to indicate such (like the rest of the devtools)

collapsed:

![screen shot 2014-12-09 at 9 28 46 pm](https://cloud.githubusercontent.com/assets/1500684/5370964/77a97b18-7fea-11e4-85cc-831b107faed4.png)

expanded:

![screen shot 2014-12-09 at 9 28 51 pm](https://cloud.githubusercontent.com/assets/1500684/5370968/8594cda4-7fea-11e4-8c66-a7cdd6385581.png)

Example arrow (what I'm talking about):

![screen shot 2014-12-09 at 9 30 14 pm](https://cloud.githubusercontent.com/assets/1500684/5370971/9a0b35b6-7fea-11e4-9e74-105b047e715a.png)

Thanks! :D

**Comment by SomeKittens** [comment]
Fixed in 0ba5f2579e03d0276e06d8fd33111a136bfe8632
