### ISSUE TITLE
Breaks manually bootstrapped apps (does not return $injector)

### ISSUE THREAD

**Issue by kentcdodds** [angular/batarang#163]
I'm not sure how this happens, but if you open [this jsbin](http://jsbin.com/ledowujabo) output in a browser without the extension (or an older version) then it works just fine. If you open it with 0.5.0, it doesn't bootstrap and there's an error in the console.

This example seems to be failing for a different reason that my app, but in both cases, angular.bootstrap is returning `undefined` instead of `$injector` as it should.

**Comment by bzitzow** [comment]
+1

> 2) angular.bootstrap isn't returning the $injector as it should when batarang is installed.

AngularJS Batarang 0.7.4

**Comment by SomeKittens** [comment]
@kentcdodds  provided this JSBin repo: http://output.jsbin.com/wehufa

**Comment by kentcdodds** [comment]
Just realized that the original had a jsbin as well that reproduces the issue :-)

**Comment by TombolaShepless** [comment]
Do we know how to fix this issue?

**Comment by SomeKittens** [comment]
This appears to happen with *all* defers of bootstrapping, not just Batarang: http://jsbin.com/silaji/edit?html,js,output

Digging through Angular.js proper to see if there's a solution there.

**Comment by SomeKittens** [comment]
From the docs:

> Note that Protractor based end-to-end tests cannot use this function to bootstrap manually. They must use ngApp.

Batarang uses the same techniques as Protractor, so this is a limitation of Angular itself.  Sorry about that folks...

**Comment by kentcdodds** [comment]
Huh... That explains why my protractor tests act funny sometimes :-) I think that I'll have to rewrite my bootstrap to do something [like this](http://jsbin.com/qaxeqi/edit?html,js,console,output) then. :-( Thanks for the tip!

**Comment by trajano** [comment]
@kentcdodds still does not work for me with Meteor.  It seems to be closed there too as a limitation https://github.com/Urigo/angular-meteor/issues/90
