### ISSUE TITLE
bug: `TypeError: Cannot read property 'replace' of undefined`

### ISSUE THREAD

**Issue by chrisirhc** [angular/batarang#166]
Batarang version: 0.6.0

Plunker: http://plnkr.co/edit/V0th8UCIE44GpQ3ZLiAi?p=preview or http://run.plnkr.co/plunks/V0th8UCIE44GpQ3ZLiAi/

Problem: Loaded a page containing some element that has both `disabled` and `ngDisabled` in its template.
![screen shot 2014-12-09 at 10 38 50 pm](https://cloud.githubusercontent.com/assets/132584/5371861/4cff4b2c-7ff4-11e4-8b73-d679a260c894.png)

Narrowed down to:
![screen shot 2014-12-09 at 10 37 48 pm](https://cloud.githubusercontent.com/assets/132584/5371864/58c234ce-7ff4-11e4-84a7-b01a505c2f19.png)

![screen shot 2014-12-09 at 10 38 34 pm](https://cloud.githubusercontent.com/assets/132584/5371867/5e4ba844-7ff4-11e4-888a-a63831c34c3c.png)

Looks like `angularAttrs` can contain attributes that may not be defined in `attrs`.

**Comment by SomeKittens** [comment]
Fixed in 0.7.1.  If this issue persists for you, make sure you're on the official Batarang and everything's up-to-date.

**Comment by snkiran** [comment]
<script type="text/javascript">  

functionExport(json_data, "User_Report", true);

function functionExport(JSONData, ReportTitle, ShowLabel) {

    var arrData = typeof JSONData != 'object' ? JSON.parse(JSONData) : JSONData;

    var CSV = '';

    

    //This condition will generate the Label/Header

    if (ShowLabel) {

        var row = "";

        //This loop will extract the label from 1st index of on array

        for (var index in arrData[0]) {

        

            row += index.toUpperCase() + ',';

        }

        row = row.slice(0, -1);

        //append Label row with line break

        CSV += row + '\r\n';

    }

    //1st loop is to extract each row

    for (var i = 0; i < arrData.length; i++) {

        var row = "";

        for (var index in arrData[i]) {

            row += '"' + arrData[i][index] + '",';

        }

        row.slice(0, row.length - 1);

        CSV += row + '\r\n';

    }

    if (CSV == '') {

        alert("Invalid data");

        return;

    }

    //Generate a file name

    var fileName = "Manage_";

   

    fileName += ReportTitle.replace(/ /g, "_");

  

    var uri = 'data:text/csv;charset=UTF-8,' + escape(CSV);

    var link = document.createElement("a");

    link.href = uri;

    link.style = "visibility:hidden";

    link.download = fileName + ".csv";

    //this part will append the anchor tag and remove it after automatic click

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

}

this is my javascript to download into csv file .. but I want to replace special characters like &amp; into &, also &lt; into <  and also &gt; into >..

**Comment by snkiran** [comment]
<script type="text/javascript">  

functionExport(json_data, "User_Report", true);

function functionExport(JSONData, ReportTitle, ShowLabel) {

    var arrData = typeof JSONData != 'object' ? JSON.parse(JSONData) : JSONData;

    var CSV = '';

    

    //This condition will generate the Label/Header

    if (ShowLabel) {

        var row = "";

        //This loop will extract the label from 1st index of on array

        for (var index in arrData[0]) {

        

            row += index.toUpperCase() + ',';

        }

        row = row.slice(0, -1);

        //append Label row with line break

        CSV += row + '\r\n';

    }

    //1st loop is to extract each row

    for (var i = 0; i < arrData.length; i++) {

        var row = "";

        for (var index in arrData[i]) {

            row += '"' + arrData[i][index] + '",';

        }

        row.slice(0, row.length - 1);

        CSV += row + '\r\n';

    }

    if (CSV == '') {

        alert("Invalid data");

        return;

    }

    //Generate a file name

    var fileName = "Manage_";

   

    fileName += ReportTitle.replace(/ /g, "_");

  

    var uri = 'data:text/csv;charset=UTF-8,' + escape(CSV);

    var link = document.createElement("a");

    link.href = uri;

    link.style = "visibility:hidden";

    link.download = fileName + ".csv";

    //this part will append the anchor tag and remove it after automatic click

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

}

this is my javascript to download into csv file .. but I want to replace special characters like &amp; into &, also &lt; into <  and also &gt; into >..
