### ISSUE TITLE
App loads as blank page

### ISSUE THREAD

**Issue by benbuckman** [angular/batarang#167]
When our Angular app loads now, and Batarang is enabled, the page is blank and the app never starts. The console shows "Angular Hint: Modules" and "Angular Hint: Controllers", no errors, but no other activity or XHRs. If I refresh the page, the app loads normally. If I disable Batarang, the blank page doesn't happen anymore.

Using the Batarang extension with Chrome 39.0.2171.71.
This started happening with some changes in our Angular app requiring HTTPS (and related App Cache shenanigans to make that work).

Any ideas?
Thanks

**Comment by SomeKittens** [comment]
Can no longer reproduce the problem against @Crashthatch's repo.  Thanks all!
