### ISSUE TITLE
Can't work with ui-select

### ISSUE THREAD

**Issue by Adam-Goldman7** [angular/batarang#173]
We use ui-select in our project, and with the latest update of batarang, it gives out the following error:

Error:
Variable "$select.setActiveItem" called on LI element does not exist in that scope. Event directive found on "<li class="ui-select-choices-row ng-scope" ng-class="{'select2-highlighted': $select.isActive(this), 'select2-disabled': $select.isDisabled(this)}" ng-repeat="member in $select.items" ng-if="$select.open" ng-mouseenter="$select.setActiveItem(member)" ng-click="$select.select(member,false,$event)"><div class="select2-result-label ui-select-choices-row-inner" uis-transclude-append=""><span class="ng-binding ng-scope">Adam</span></div></li>".

![image](https://cloud.githubusercontent.com/assets/6963212/5374000/0d80ea76-8064-11e4-87d4-4f0fa48e284a.png)

When I remove batarang it works :)

**Comment by astrism** [comment]
@btford I found that testing using a plnkr did not produce the problem. Additionally when I test on my on production site its not a problem. The problem only manifests when running on localhost as seen in the screenshot. To reproduce download a zip of the plnkr using the link below and run it in a local server. Just opening the file using file protocol wont do it.

http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview

**Comment by bartvanremortele** [comment]
I've had an issue with ui-select aswell. Mainly when the autocomplete has result labels I seem to be unable to click on them when having Batarang installed. Pressing enter selects the autocomplete just fine. I have this issue with a tagging implementation (example can be found here: https://github.com/angular-ui/ui-select/blob/master/examples/demo-tagging.html)

**Comment by SomeKittens** [comment]
Tested with 0.8.7, this works now.
