### ISSUE TITLE
feat: Performance tools

### ISSUE THREAD

**Issue by danmindru** [angular/batarang#188]
Are performance tools gone forever? They where quite helpful...

**Comment by cesarandreu** [comment]
:+1:

**Comment by LeleDev** [comment]
Please if you can put this back soon... it's really a core feature

Many users are rating batarang badly and won't use batarang anymore just because they don't even know about the existence of the dropped features. It was vital for me, and I'm not able to install old versions as suggested (I followed the instructions, the tab angularjs appears but it is empty). I'm on Fedora 20, 64bit...

Thank you in advance

**Comment by vitalybe** [comment]
I was looking around but I can't seem to find any other tool that can do that. Only semi-related things I found are:

* Count amount of watchers: https://chrome.google.com/webstore/detail/angular-watchers/nlmjblobloedpmkmmckeehnbfalnjnjk?hl=en
* Count amount of watchers + Time of total digest: https://github.com/kentcdodds/ng-stats

Neither, however, allow you to profile the time spent on specific watch expression :(

**Comment by pkaminski** [comment]
I wasn't able to find an alternative for Angular digest profiling, so I built one that I think improves on what used to be available in Batarang in some ways: https://github.com/pkaminski/digest-hud

**Comment by seiyria** [comment]
@pkaminski that looks nice, thanks!

**Comment by JoshSchreuder** [comment]
The legacy version of Batarang which has the performance tab is on the Chrome store:
https://chrome.google.com/webstore/detail/angularjs-batarang-stable/niopocochgahfkiccpjmmpchncjoapek

**Comment by SomeKittens** [comment]
Hello!  I'm the contributor who's working on the perf tools.  You folks deserve an update.

Currently, `angular-hint` (the engine behind Batarang) is listening to and emitting details about the digest cycle.  Woo!  I'm currently working on re-adding the perf pane itself (which also manages the absolute gobs of perf data hint is throwing around).

Unfortunately, I don't have a good eta - I just started a new job so things are a bit bonkers.

As an aside, we don't recommend the legacy version of Batarang (among other things, it won't receive updates and breaks bind-once)

**Comment by SomeKittens** [comment]
PR for performance tools is here: https://github.com/angular/batarang/pull/259

**Comment by SomeKittens** [comment]
Perf tools are back!  https://github.com/angular/batarang/commit/f8359a9f410a173397f461a6ffc14c4b52ad2990

**Comment by danmindru** [comment]
Thanks so much @SomeKittens :)
:+1:

**Comment by Splaktar** [comment]
That's great! Thank you @SomeKittens

**Comment by erwinmombay** [comment]
@SomeKittens thanks!
