### ISSUE TITLE
Hints doesn't accept single lowercase word as lowerCamelCase

### ISSUE THREAD

**Issue by andrewjli** [angular/batarang#189]
As per the title, Hints doesn't accept a single lower case word as a valid lowerCamelCase name. I'm not sure if this is considered correct behaviour or not. Perhaps it's bad practice to use one-word names for modules. This is in Batarang 0.7.1.

Screenshot:
![](http://puu.sh/dpIXR.png)
(ignore the `federicot.ng-message-center`. That's someone else's module)

Also shown in the screenshot:
Modules section displays a message about Controller naming even though there is a separate section for Controllers if there are controller naming issues, and there are currently no Controller related naming issues.

**Comment by SomeKittens** [comment]
This is fixed here: https://github.com/angular/angular-hint/commit/cb55c9a510ee47c79f25e54727956014627ad188
