### ISSUE TITLE
bug(v0.6.0): button clicks not working after latest update of Batarang installed

### ISSUE THREAD

**Issue by venkatesh-tr** [angular/batarang#190]
I have a login page on which a login button is provided for user to login. My application is using AngularStrap + Bootstrap CSS + few other plugins for angularjs. It was working till yesterday's update for Batarang. After this update, the click of every button in the application stopped working.

It works if I disable the Batarang plugin, but fails to work in case of enabling this extension. Please look into the issue and let me know if something is broken.

**Comment by SomeKittens** [comment]
There have been several fixes in the area of click events.  Closing this.  If anyone manages a reproduction we can reopen.
