### ISSUE TITLE
I need your help!

### ISSUE THREAD

**Issue by btford** [angular/batarang#194]
Following the v0.5.0 release, I wanted to thank everyone that posted reproductions and stack traces, and sent me PRs to fix the issues with the new implementation. I wouldn't have been able to follow-up with fixes if not for your help.

It's clear to me that I haven't given the time to Batarang that it deserves. Several people have forked, or created other extensions to try and fill these gaps. I'd like to invite anyone interested to work with me on making Batarang better.

My priority with Batarang right now is to first [improve the testing infrastructure](https://github.com/angular/angularjs-batarang/issues/193), and then reduce some of the complexity of it's implementation ([especially WRT angular-hint](https://github.com/angular/angular-hint/issues/64)). I want to make sure nothing like the issues we say in v0.5.0 happens again, and also make it easier for others to contribute and reason about the code.

After that, I'm happy to provide guidance as far as new features and improvement, but I'm hoping to get others involved so this project continues to have good momentum even when my focus is on other things (like github.com/angular/router ).

If you're interested in helping, please comment and let me know how you'd like to see Batarang improved. Thanks!

**Comment by levithomason** [comment]
I've been using Batarang for just about 2 years now.  I've run into some issues with the latest build.  I'd love to help.

I'm experienced enough with gulp, protractor, and selenium.  Where is the most helpful place to plug in?

**Comment by scheffield** [comment]
I'd like to help as well. Where can/should I start?

**Comment by chino23** [comment]
@btford so is this officially dead? what a shame...

**Comment by SomeKittens** [comment]
Anyone who wants to help can start by tackling an issue in the https://github.com/angular/angular-hint project (the engine behind Batarang).
