### ISSUE TITLE
Batarang in Chrome Version 39.0.2171.95 m

### ISSUE THREAD

**Issue by tomalex0** [angular/batarang#198]
Recently i see the batarang UI has changed in my latest chrome, i no longer see performance tab and dependency. Is there any issue.

If below is latest version of batarang , do you have guidelines to  use this.

![batarang](https://cloud.githubusercontent.com/assets/208168/5460742/31218c82-851a-11e4-90b9-c96885225de1.PNG)

**Comment by SET001** [comment]
this is still an issue, why close?

**Comment by diosney** [comment]
Yeah, is happening to me too, I really don't know if this is a bug or a whole new way to use it.

Any guidance here?
