### ISSUE TITLE
Multiple mouse events on the same element do not work

### ISSUE THREAD

**Issue by engelfrost** [angular/batarang#205]
When I place multiple mouse event directived on the same element only one of them work:

```
<a ng-mouseover="openDropdown($index)" ng-mouseleave="closeDropdown($index)" ng-click="toggleDropdown($index)">...</a>
```

If I disable the Batarang extension the code works, but with Batarang enabled only one of the directives work. 

(I don't think you'll need it, but the full code I'm working with is available here, build and run /test/manual.html: https://git.diversity.io/textalk-webshop-native-components/tws-top-menu/tree/a6b8f25f967bdf28cf30846e13c70874725da4dc)

**Comment by darielnoel** [comment]
+1

**Comment by Swoogan** [comment]
I was also bitten by this bug. I posted to SO: http://stackoverflow.com/questions/29090162/ng-mousedown-handler-attaching-to-ng-mouseups-event

Here's a minimal test:

    <!DOCTYPE html>
    <html>
       <body ng-app>
         <div>
           <div style="background-color: blue; width: 80px;" ng-mousedown="count = count + 1" ng-mouseup="count = count - 1" ng-init="count=0">Click Me</div>
           <div>{{count}}</div>
         </div>
         <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
       </body>
     </html>

I'm a little perturbed by how much time this issue cost me. I only installed this extension a couple of days ago and the only thing it did was break my code.

**Comment by ram535ii** [comment]
+1

**Comment by engelfrost** [comment]
Tip: At the moment I've switched to ng-inspector instead.

**Comment by nicholasjgreen** [comment]
:+1:

**Comment by richyarD** [comment]
Turning off Batarang extension in Chrome helped me! :+1:

**Comment by gary-b** [comment]
This issue is fixed in the latest Batarang. Created repro here: here https://localhost:63355/ng-version-test-apps/app/v4/index.html
