### ISSUE TITLE
batarang breaks angular-foundation topbar

### ISSUE THREAD

**Issue by diefans** [angular/batarang#206]
with this plugin the top-bar directive is ignored sometimes

I also feel the app sluggish with this plugin enabled

**Comment by btford** [comment]
Can you please provide a reproduction via [jsbin](http://jsbin.com/), [plnkr.co](http://plnkr.co), or [jsfiddle](http://jsfiddle.net/)?

This saves us a lot of time. Thanks!

**Comment by diefans** [comment]
I have an app, which is not really a single page application, where I use foundation for the menu. A click on the menu reloads the page. With batarang a reload of the page by clicking a link in the menu makes angular-foundation stop - so that the menu is not renderered with styles but instead I see the UL/LI list elements...

deinstalling/disabling batarang solved this...

It seemed to me that some angular specific modules were not running properly on reload as in the first page load...

There is one warning in the console: 
```
(index):3140 The specified value 't' is not a valid email address.
```
I guess (index):3140 points somewhere in batarang


Without advertising - you can see it in action at http://krisztina-berger.com

**Comment by erwinmombay** [comment]
im not 100% sure but that seems like its modernizr

**Comment by SomeKittens** [comment]
Does not reproduce with latest master, so I'm calling this fixed unless proven otherwise.
