### ISSUE TITLE
Batarang prevents ng-blur and ng-focus working when on same element 

### ISSUE THREAD

**Issue by jakefoster** [angular/batarang#211]
Given this markup:

```html
<input type="text" class="form-control" name="name"
                   ng-blur="onNameBlur()"
                   ng-focus="onNameFocus()" />
```

Only the first (in this case ng-blur) will fire.  If the order is reversed then only ng-focus would fire.

Disabling the extension corrects the issue.

**Comment by btford** [comment]
Possibly related to #205

**Comment by ram535ii** [comment]
+1

**Comment by peternixey** [comment]
Same here

**Comment by nicholasjgreen** [comment]
:+1:

**Comment by iorlas** [comment]
Spent 6 hours in debugging. This should be fixed ASAP or just workaround should be provided(like big red button to enable/disable?).

**Comment by gary-b** [comment]
This issue is fixed in the latest Batarang. Created repro here: 

http://gary-b.github.io/ng-version-test-apps/app/v3/index.html

**Comment by btford** [comment]
:+1: Thanks for confirming, @gary-b
