### ISSUE TITLE
doesn't work with google apps scripts

### ISSUE THREAD

**Issue by ittayd** [angular/batarang#238]
I'm using a deployed web app created with Google apps scripts (GAS). It has a model of putting the script code in an IFrame which Batarang seems not to handle. The panel in the developer tools is empty

**Comment by SomeKittens** [comment]
There's a known race condition where the panel is empty regardless of app state.  Can you try a few more times & see if you can get the devtools panel to appear?

**Comment by ittayd** [comment]
I could never get the dev tools panel to appear

**Comment by SomeKittens** [comment]
Ah, re-reading this, the problem lies in the `iframe`.  Dupe of #14
