### ISSUE TITLE
Unterminated quote when string contains some chars

### ISSUE THREAD

**Issue by pixsrv** [angular/batarang#239]
folowing lines cause angular to show error
```html
<div ng-click="foo('abc!')"></div>
<div ng-click="foo('abc&')"></div>
```
Error: $parse:lexerr
Lexer Error: Unterminated quote at columns ... ['abc] in expression [foo'abc].

but of course these two don't
```html
<div ng-click="foo('abc')"></div>
<div ng-click="foo('abc')"></div>
```

(escaping doesn't help)

EDIT: this works well
```html
<div onclick="foo('abc!')"></div>
<div onclick="foo('abc&')"></div>
```

strange thing:
when i add ng-click as above using jQuery with .attr() then error occurs
but when i add it by .data() then it doesn't occur

switching off batarang "fixes" the problem ;)

angular v1.3.15
batarang v0.8.2

**Comment by gkalpak** [comment]
BTW, this is more likely an angular-hint issue and possibly addressed by [angular-hint#101][1].
(Not sure though, as it might qualify as one of the unadressed edge cases.)

[1]: https://github.com/angular/angular-hint/pull/101

**Comment by erwinmombay** [comment]
this should be fixed by the linked hint PR. appreciate you linking it! i'll see if i can add a test for it.

**Comment by erwinmombay** [comment]
fix landed in https://github.com/angular/angular-hint/commit/26cfc749113a599a1e11a587091c558ee2e499b6
