### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by pulkitnandan** [angular/batarang#252]
It say's build fails.

**Comment by SomeKittens** [comment]
Can you provide more details?  What did you run to get that?  Is this building the code, or an error in the extension itself?  Does it consistently reproduce?

**Comment by pulkitnandan** [comment]
In readme.md @ https://github.com/angular/batarang

It 
![image](https://cloud.githubusercontent.com/assets/5687927/9274220/68a69210-42b1-11e5-8f65-5428af8fee49.png)

**Comment by SomeKittens** [comment]
That's an issue we're currently having with TravisCI.  Yes, the plugin is functioning.
