### ISSUE TITLE
Angular with Breeze + other plugins causes a ng.injector is not a function

### ISSUE THREAD

**Issue by ganySA** [angular/batarang#262]
I am trying to use batarang with breezejs.

Similar problems with other plugins:
http://stackoverflow.com/questions/27403772/angular-ui-typeahead-batarang-conflict

**Comment by SomeKittens** [comment]
- Are you using the Batarang plugin (and not the "Batarang Stable" plugin, which is not associated with this project)?
 - What version do you have?
 - Can you create a small example that reproduces the issue?

**Comment by ganySA** [comment]
Hi

I am using batarang  0.8.7. Angular Batarang  0.8.7

I do not have an example. But the minute i click the enable tick box i get and when i remove it the problem goes away.

```Uncaught TypeError: ng.injector is not a functionproto.initialize @ breeze.debug.js:15927initializeAdapterInstanceCore @ breeze.debug.js:1874__config.getAdapterInstance @ breeze.debug.js:1822breeze.AbstractDataServiceAdapter.proto.initialize @ breeze.debug.js:15568initializeAdapterInstanceCore @ breeze.debug.js:1874__config.initializeAdapterInstance @ breeze.debug.js:1795__objectMap @ breeze.debug.js:56__config.initializeAdapterInstances @ breeze.debug.js:1769(anonymous function) @ breeze.debug.js:17513def @ breeze.debug.js:10breeze.version @ breeze.debug.js:20(anonymous function) @ breeze.debug.js:23
breeze.savequeuing.js:56 Uncaught Error: Can't find breezeEntityManager @ breeze.savequeuing.js:56(anonymous function) @ breeze.savequeuing.js:58
breeze.bridge.angular.js:81 Uncaught Error: Can't find breezeangular.module.$provide.provider.breeze @ breeze.bridge.angular.js:81(anonymous function) @ breeze.bridge.angular.js:83
angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.10/$injector/modulerr?p0=MetronicApp&p1=Err…2Fprac%2Fassets%2Fglobal%2Fplugins%2Fangularjs%2Fangular.min.js%3A17%3A350)(anonymous function) @ angular.js:38(anonymous function) @ angular.js:4117s @ angular.js:323g @ angular.js:4078Ob @ angular.js:4004d @ angular.js:1446ga.resumeBootstrap @ angular.js:1475maybeBootstrap @ hint.js:514```

**Comment by SomeKittens** [comment]
Unfortunately I don't have any experience with BreezeJS.  If you can create a reproduction case, we can fix this.  Otherwise, I don't have anything to go on.

**Comment by gary-b** [comment]
Hrm, I haven't used breeze.js before either. I found this little demo app http://run.plnkr.co/plunks/upp7wB/ and I don't get any js errors in the console with it.

**Comment by SomeKittens** [comment]
Thanks for the Plunkr, @gary-b.  Closing this as no repro now.  @ganySA if you get a self-contained reproduction, I'll open this back up.
