### ISSUE TITLE
angular.module(...).decorator is not a function

### ISSUE THREAD

**Issue by op1ekun** [angular/batarang#275]
When batarang is on there's no .decorator() method in angular.module API.

Example:
```
angular.module( 'Demo', []);

angular.module('Demo')
    .factory('greeting', function greetingFactory() {
        // I return a greeting for the given name.
        return function (name) {
            return "Hello " + name + "." ;
        }
    });

angular.module('Demo')
    .decorator('greeting', function greetingDecorator($delegate) {

        return function() { 
            return $delegate(name) + ' How are you doing?';
        };
    });
```

Trying to call .decorator() gives me:
```
angular.module(...).decorator is not a function
```

ENV:
System: WIndows Server 2012 R2
Chrome: 46.0.2490.80 m
Plugin: 0.10.1
Angular: 1.4.7

**Comment by karptonite** [comment]
I can confirm that this is an issue. Angular 1.4.7.

**Comment by erwinmombay** [comment]
will look into it

**Comment by Narretz** [comment]
Can we possibly maybe fix .decorator and .component close to the 1.5 release (which may happen before Christmas)? I can help with the implementation.

**Comment by erwinmombay** [comment]
@Narretz for sure, i haven't had a chance to look at this yet (really sorry!). we have a hangouts this thursday at 2pm PST if you wanted to talk about it! if not feel free to leave any info here :+1:

**Comment by Narretz** [comment]
We prefix the loader with this line:
```
function isFunction(value) {
  return typeof value === 'function';
}
```
I updated the PR.
I still get `component is not a function` though, no idea what's up with that.

**Comment by petebacondarwin** [comment]
Is there a PR for this yet? If not I think @Narretz will knock one up, right?

**Comment by petebacondarwin** [comment]
Oh I just saw that it is here: https://github.com/angular/batarang/pull/284
