### ISSUE TITLE
Can't disable Batarang

### ISSUE THREAD

**Issue by royaldark** [angular/batarang#276]
When I uncheck the "Enable" box in Batarang, the page reloads, but Batarang continues to run. Closing and reopening Chrome fixes the issue. This is an issue mainly because it makes JS profiles extremely inaccurate, as most of the CPU time is spent in Batarang's `hint.js`.

Screenshot of Scopes still loading while checkbox is diabled:
![screenshot from 2015-11-03 23-19-46](https://cloud.githubusercontent.com/assets/1669397/10930201/b5761df8-8281-11e5-973f-70f83a73c4ef.png)

I'm running Chrome 46 with Batarang 0.10.1 on Ubuntu 15.10.

**Comment by SomeKittens** [comment]
What happens if you only close/reopen the tab?

**Comment by royaldark** [comment]
I haven't encountered this issue again, so I'm closing this issue due to lack of repro.
