### ISSUE TITLE
Batarang produces errors after Angular upgrade to 1.5

### ISSUE THREAD

**Issue by Kapaacius** [angular/batarang#285]
I upgraded angular to 1.5 and this caused Batarang to produces errors to console.
Here's an example:

```
TypeError: Cannot read property '$id' of undefined
    at arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2001:19)
```

**Comment by iltera** [comment]
I am also getting the same error after upgrading to version 1.5

Is there any way to overcome these errors?

**Comment by gkalpak** [comment]
Could someone provide a live demo (e.g. using CodePen, Plnkr etc) ?

**Comment by oarcher** [comment]
I have the same problem, even on a 'hello world' example without ng-controller.

**Comment by SomeKittens** [comment]
ditto on the live demo - we can't do much without a repro.

**Comment by Narretz** [comment]
Check this plnkr, http://plnkr.co/edit/irPNf9sFY5LLRKSwvcsN?p=preview, BUT not in the edit view or the embedded view -> instead "launch  the preview in a separate window" (little blue button in the preview window). The app still works, but you get the error from above.
I've tried it locally and a simple app still works, but it looks like every digest triggers that error.

**Comment by SomeKittens** [comment]
Was able to repro.  Looks like we're making some assumptions about the `this` value of the reaction function inside a watcher.  Not up to date on 1.5 internals - what changed?

**Comment by Narretz** [comment]
Looks like this here https://github.com/angular/angular.js/commit/1c6edd416b4baad0c8b01148f429eb78e0ad7eaa

**Comment by gkalpak** [comment]
I have a submitted a fix https://github.com/angular/angular-hint/pull/117.
Thx @Narretz for the repro (I wouldn't have tried it myself :smiley:).
