### ISSUE TITLE
Angular one way binding doesn't work when batarang is on.

### ISSUE THREAD

**Issue by lukaszTrackback** [angular/batarang#289]
f I run simple code under Windows 10 Chrome (tested on angular 1.4.9 and 1.5.0) and enable Batarang(0.10.7) angular seems to ignore one time binding. **[More.](https://github.com/angular/angular.js/issues/14203)**

**Comment by turtlemonvh** [comment]
I'm seeing something similar with batarang 0.10.7 and angular v1.4.9.

Here's a screen shot of some watches that are still showing up as triggered. (uploaded to imgur because github's file upload kept flaking out).

![Batarang Bug](http://i.imgur.com/3FH5tfX.gif)

**Comment by shyamal890** [comment]
I don't see this issue on my side. Windows 7, latest chrome.

**Comment by SomeKittens** [comment]
This issue was fixed some time ago.  Make sure you're on the latest version.  Will reopen if there's a repro case against the latest version.

**Comment by EricBorlandAGS** [comment]
I have the same problem on Chrome for Mac with Batarang 0.10.7 and angular 1.5...

**Comment by SomeKittens** [comment]
@EricBorlandAGS That's nice but useless without a repro case.  Can you post a snippet of code that reproduces the problem?

**Comment by jacek213** [comment]
I also have this problem. Verson 0.10.7, Google Chrome	51.0.2704.106 (Official Build) (64-bit), ubuntu 14.04.

![image](https://cloud.githubusercontent.com/assets/3914691/16583963/4a6f003a-42b9-11e6-8031-5e33f56ced46.png)
