### ISSUE TITLE
Why can't we see more of the digest timings?

### ISSUE THREAD

**Issue by denizdogan** [angular/batarang#291]
What are the plans ahead for the Performance tab?

Why can't I see _all_ digest timings, but rather just the last 30? I am building a complex application where the initial payload can trigger hundreds of digests, which I am now unable to debug due to this.

**Comment by SomeKittens** [comment]
Perf tab maintainer here.  To be honest, there's a ton I'd like to do but Google's essentially dropped support for this project so it's wasted time until we can get a better way to release things.  I'll merge a PR but as of right now am not writing any code for this project.

**Comment by denizdogan** [comment]
No longer relevant to me, closing
