### ISSUE TITLE
Missing models, options and help panels

### ISSUE THREAD

**Issue by scarrick68** [angular/batarang#292]
I downloaded the extension and it only has enable, scopes, hints and performance (alpha) panes. It doesn't show models or dependencies panes and watch expressions / watch tree are not present under the performance tab. The extension I got doesn't look anything like what's shown in the youtube video embedded in the overview section on the chrome app store.

**Comment by SomeKittens** [comment]
The YouTube video shows an older version of Batarang (see #269 )
