### ISSUE TITLE
Trouble Enabling batarang in Version 46.0.2490.71 

### ISSUE THREAD

**Issue by Ajishapj** [angular/batarang#295]
Hi All
I am new to angular and trying to enable chrome extension for debugging angular app

my chrome version is Version 46.0.2490.71 and i have downloaded Batarang latest version available in  Github.and added in chrome://Extensions and enabled it.
I can see AngularJs tab while i open developer tool ,but the sub tabs inside the angular tab is missing and i am unable to enable it ,Please see the screen shot and let me know if i am missing anything ? any settings? 
![subtabs](https://cloud.githubusercontent.com/assets/19320317/15205544/d477d4d6-1835-11e6-87b8-12c071de3969.jpg)

**Comment by gkalpak** [comment]
I haven't seen that before. Can you inspect the Batarang Extension background page (from chrome://extensions/) and see if there are any errors there ?

**Comment by jycouet** [comment]
I have the same issue.
I checked the Extension log, but there is nothing. I'm using version 10.7.

Do you have any idea?

**Comment by SomeKittens** [comment]
If you update Chrome (you're 5 major versions behind, seems like a good idea) does it work?  I don't think supporting past versions is in scope for this project.

**Comment by carlosromel** [comment]
@Ajishapj, @gkalpak, @jycouet, @SomeKittens are you still using Chrome at versions prior to 52?
Maybe this issue can be closed, due the time lapse.

**Comment by jycouet** [comment]
For me you can close it :)
