### ISSUE TITLE
HIPAA Compliant?

### ISSUE THREAD

**Issue by jarmanizc** [angular/batarang#299]
Our organization would like to use this Chrome extension for debugging our web-based electronic medical records system.  However, since this system includes protected healthcare information, we need to be certain that the extension doesn't send any private browsing data back to another server or anything.  Does anyone know if this is the case?

**Comment by SomeKittens** [comment]
I can't say, as we rely on a lot of libraries outside of our control.  Your best bet is to dig through the codebase yourself.
