### ISSUE TITLE
Not working on Chrome Beta (53+)

### ISSUE THREAD

**Issue by alfmatos** [angular/batarang#303]
Hi, just gave this a run on an angular app with ``Chrome Version 53.0.2785.34 beta (64-bit)``, and the AngularJs tab appears blank.

I've checked the background page on the extensions, and it shows content, but nothing seems to happen.

Thoughts?

**Comment by SomeKittens** [comment]
Please include a reproduction case, otherwise we're just left guessing.  I'll reopen when there's a repro.

**Comment by felixruponen** [comment]
+1
