### ISSUE TITLE
Batarang not working with Chrome Version 53.0.2785.143 (64-bit)?

### ISSUE THREAD

**Issue by bayy** [angular/batarang#305]
I noticed that nothing shows up on AngularJS tab with Chrome Version 53.0.2785.143 (64-bit). Anyone has the same problem?

Thanks,

![screen shot 2016-10-05 at 8 55 36 am](https://cloud.githubusercontent.com/assets/2373656/19118406/87003074-8ad9-11e6-94c8-b9033a4f22b1.png)

**Comment by gkalpak** [comment]
It works for me. Make sure you refresh the webpage with the DevTools open (and Batarang enabled).

**Comment by bayy** [comment]
Thanks.
