### ISSUE TITLE
Please build a Release 0.10.8. from current HEAD

### ISSUE THREAD

**Issue by maknesium** [angular/batarang#309]
Hi,

I just wanted to ask you politely if it would be possible to build a new release with the current fixes (so batarang can be used with angularjs 1.6.3+) and upload it to the Chrome Web Store.

Yesterday, I built the current HEAD myself (named it 0.10.8) and verified that it is working with angular 1.6.3 and distributed the package within the company for all the other developers - who now have to install the extension from a ZIP file.....

It would be so much nicer (and more trustworthy) if everybody could download the extension from the Chrome Web Store.

Thank you very much :)

**Comment by gkalpak** [comment]
v0.10.8 is out, but it's broken. Tracking in #310.
