### ISSUE TITLE
0.10.8 broken

### ISSUE THREAD

**Issue by BigGillyStyle** [angular/batarang#310]
OS: macOS 10.12.4
Chrome: 57.0.2987.133 (64-bit)
Batarang: 0.10.8

This extension was working fine until this morning when I assumed it updated to 0.10.8.  I can examine scopes, but if I click the "Enable" checkbox in the AngularJS tab within the Chrome DevTools I get the following error many times and the extension crashes:

```
VM859 extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (VM859 extensions::schemaUtils:112)
    at Object.<anonymous> (VM854 extensions::binding:411)
    at Object.<anonymous> (VM853 extensions::runtime:129)
    at Object.handleRequest (VM854 extensions::binding:63)
    at Object.<anonymous> (VM854 extensions::binding:422)
```

(probably separate issue) I following the Readme instructions to downgrade to 0.10.7 (after removing 0.10.8), but the AngularJS tab is just an empty page.  I tried the Chrome Beta channel as well using 0.10.8, but I got the same JS error in the console.

**Comment by gkalpak** [comment]
Thx for reporting. We are aware and working on a fix. Expect v0.10.9 soon :grin:

**Comment by JoshSchreuder** [comment]
Thanks for updating @gkalpak, glad to see Angular 1 tooling is still being maintained 😄

**Comment by gkalpak** [comment]
v0.10.9 has been uploaded to the Chrome Web Store. Should be published in a few mins.

**Comment by BigGillyStyle** [comment]
Totally fixed my issue.  Thanks @gkalpak ...that was a faster response than I ever expected 😄

**Comment by gkalpak** [comment]
Well, if you break it, you have to fix it :wink:
That said there seems to be another issue with false reports: "Module X was created but never loaded." 😞
