### ISSUE TITLE
Blank screen in AngularJS tab in Developer Tools

### ISSUE THREAD

**Issue by PranKe01** [angular/batarang#316]
Hi there,
I am working with AngularJS 1.4.7 and wanted to use this extension. With the current version 0.10.* the whole AngularJS tab in the Developer Tools windows is blank. I also tried v0.8.*. When using 0.4.* some content is shown, but the most functions do not work (like scopes).

Is there a version which works with AngularJS 1.4.7? Or do I need to "tweak" my project, to make it work? Is it mandatory to have a ng-app defined?

I am using Google Chrome v59.

I also tried Google Chrome v45 with Batarang 0.8.7 and 0.4.3 and still it does not work. Even the page https://angularjs.org/ does not show anything in the AngularJS tab.

Thanks in advance.

**Comment by gkalpak** [comment]
The latest version (0.10.9) works fine for me on https://code.angularjs.org/1.4.7/docs/api (which runs AngularJS 1.4.7) 😕 
(Using Chrome 59.)

**Comment by PranKe01** [comment]
I don't know why, but today it is showing up in the AngularJS tab :) On the Angular docs page, it is showing the scopes etc. But in my application the scope is empty and in the perofmance tab "Waiting for first digest cycle..." is written :| Any ideas why? The Hints tab is filled with hints.

**Comment by gkalpak** [comment]
Nope 😞 Is the application publicly accessible?

**Comment by PranKe01** [comment]
No it's not :( Any ways to send you something like a error-log of the extension?!

**Comment by gkalpak** [comment]
Not really. You can check for any errors in the DevTools (on the tab that runs the application) or on the DevTools for the AngularJS panel (undock the application's DevTools and click <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) or on the DevTools for the extension's background page (go to `chrome://extensions/`, scroll to the extension and click on `background page` (or something along those lines)).

But I am afraid there is only that much we can do without a live reproduction of the issue 😕

**Comment by PranKe01** [comment]
I already checked the background page, but there is no error logged :| Thanks anyways. Will develop without the tooling support.

**Comment by gkalpak** [comment]
Sorry I could help more 😞
Closing for now. Happy to reopen and investigate if there is a (public) reproduction :smiley:
