### ISSUE TITLE
In chrome devlopment tools window AngularJS tab shows blank window

### ISSUE THREAD

**Issue by flash5452** [angular/batarang#321]
After following the installation instructions and installing package v0.10.9, I opened the  chrome devlopment tools window. The AngularJS Tab shows blank. Nothing is there. 
![blank-option](https://user-images.githubusercontent.com/11783550/36136227-6599fd30-10b5-11e8-8efc-0c5db70ffc08.png)

Chrome version - Version 64.0.3282.140 (Official Build) (64-bit)
OS - ubuntu 16.04 LTS and 
- windows 10 - version 1709, build 16299.192

**Comment by gkalpak** [comment]
That is weird. It works for me :grin:
Can you try to look if you get any errors in the extensions background page? (You can get to the background page of the extension in chrome://extensions/.)

**Comment by flash5452** [comment]
I do not see any errors clicking the background page. I assume I do not have to inspect on an angularjs application to see the tool options, right? @gkalpak  which version of batrang are you using and what version of chrome?

**Comment by manfwh** [comment]
ctrl+f5

**Comment by gkalpak** [comment]
@flash5452, yes you should be seeing the batarang panel in any page.
If you right-click + Inspect on the AngularJS DevTools panel, what do you see in the `Elements` panel?

**Comment by flash5452** [comment]
@manfwh nothing changed
@gkalpak I see the html source code
![dev tools](https://user-images.githubusercontent.com/11783550/36210590-d0b67f0c-11c4-11e8-8d41-cc58b4584229.png)

**Comment by gkalpak** [comment]
@flash5452, it seems like you right-clicked on the main page. Try right-clicking on the **AngularJS DevTools panel**.

**Comment by flash5452** [comment]
@gkalpak 
Is it fine, please see the snapshots
![dev tools1](https://user-images.githubusercontent.com/11783550/36245064-330382ce-124f-11e8-9a65-503acd7e8187.png)
![dev tools2](https://user-images.githubusercontent.com/11783550/36245065-333dbe30-124f-11e8-94d7-531503a255a7.png)

**Comment by gkalpak** [comment]
It seems that you are using a local unpacked extension (loaded from `~/flash5452/chrome-tools/batarang-0.10.9`).
Maybe that is causing the issues. Could you install the extension from the webstore?

**Comment by flash5452** [comment]
@gkalpak I installed from the webstore and I see the options in angularjs window...Thanks !!
But I do not see the Model Tree option
![no-model-tree](https://user-images.githubusercontent.com/11783550/36257441-e48ddfee-127c-11e8-99c0-8f6828bd9441.png)

**Comment by gkalpak** [comment]
Great! What is the Model Tree option? 😕

**Comment by flash5452** [comment]
![modal_tree_menu](https://user-images.githubusercontent.com/11783550/36276928-5ab78f8e-12b5-11e8-8fb8-bdb50cd77011.png)
The modal tree is missing and the menu also looks different
The above snapshot is from a demo video from youtube - https://www.youtube.com/watch?time_continue=101&v=q-7mhcHXSfM

**Comment by gkalpak** [comment]
Oh, I see. The layout and appearance have changed a bit. The equivalent of the `Model Tree` tab is now called `Scopes`. I am going to close this issue, since you were able to get the extension working, but feel free to continue the discussion below.

**Comment by flash5452** [comment]
ok thanks
