### ISSUE TITLE
Batarang cannot find my scopes

### ISSUE THREAD

**Issue by sbadame** [angular/batarang#39]
I am devloping an angular js webpage locally but batarang doesn't appear to do anything when I enable it. I do see the page refresh, but none of the scopes, or events register.

I have downloaded a local copy of minified AngularJS v1.0.2 
I have AngularJS Batarang 0.3.0

background.html doesn't print anything to the console.

**Comment by derekwebb** [comment]
Using:

Ubuntu 14.04.1 LTS
Chrome 39.0.2171.65
Batarang  0.4.3 stable

I am getting the same issues that were evidently present way back in 2013 with bradw2k et. al. I checked the allow local files in the extension settings and re-enabled several times. No gold. I guess I will try ng-inspector. Hope it functions. -_- Console.log just isnt cutting it for me but I guess if all else fails, it will have to do.

**Comment by tgoyer** [comment]
I've been using ng-inspector for awhile since Batarang was borked.  It works pretty well.

**Comment by derekwebb** [comment]
Yeah I tried it a minute ago. I set it to allow local file useage and all that. Fired up a new Chrome instance, and found that it too was unresponsive. Clicking on the new Angular icon (top left corner in the browser) was doing nothing at all. Oh well... Guess it must be my setup or something. Perhaps it may be getting interference from one of my other extensions? Thanks anyway!

**Comment by tgoyer** [comment]
Maybe an extension like AdBlocker or something is interfering?

**Comment by derekwebb** [comment]
Well, I don't use an ad blocker, however I do use FlashControl to prevent flash from displaying by default. It crashes too much to be trusted.

My extensions:

ColorZilla 0.5.5
FlashControl 6.13.0
JSON Editor 3.3.0
Nimbus Screenshot 6.2.0
YSlow 3.1.2

Sometime I might try turning them off and giving it another whack but for now I am just going to console.log and hope for the best. Thanks again!

**Comment by tgoyer** [comment]
No worries!  Good luck!

**Comment by is0sceles** [comment]
I was getting CANNOT GET/  when I tried enabling Batarang. I turned off AdBlocker like @tgoyer  suggested and voilà !

**Comment by BiiSmiiLLAH** [comment]
I had the same probleme. There is two version of angularjs batarang in the store, I took the stable one not the lastest obviousely but it works.
