### ISSUE TITLE
Shows no models etc.

### ISSUE THREAD

**Issue by prashantjain68** [angular/batarang#52]
![Screen shot 2013-02-12 at 3 18 12 PM](https://f.cloud.github.com/assets/2547563/151138/a9adafe4-756a-11e2-9761-d57c37d54787.png)

I downloaded the Batarang extension and tried it in both Chrome and Chrome Canaray. But it doesn't seem to show me any Angular related data.

What am I doing wrong?

**Comment by jamie-pate** [comment]
is there a separate bug for the non-file problems I am having when not using ng-app (manual bootstrap)
It seems like this is actually two separate issues!

I get the scope elements in the scope view, but the models are empty.

**Comment by SomeKittens** [comment]
Using Batarang with files served via `file:///` is covered in https://github.com/angular/batarang/issues/79

Manual bootstrapping is covered in https://github.com/angular/batarang/issues/163
