### ISSUE TITLE
Disable batarang in production?

### ISSUE THREAD

**Issue by randallb** [angular/batarang#53]
Is there a clever way to disable Batarang so various folk can't inspect my application when it's live on the real internet? I realize it's security through obscurity, but just curious.

Edit: I withdrew thinking this was a good idea. It's not.

**Comment by TheCrow1213** [comment]
+1, Should I be worried that any dev could inspect my controller's scope in a production environment?

**Comment by gkalpak** [comment]
@TheCrow1213, any dev can inspect your controller's scope in a production environment - with or without Batarang; with or without Angular. It's not something that you should be worried though.

(If your app's secutiry depends on obscurity, then you are doing it wrong - it's clinet-side code; the user can do anything with it.)
