### ISSUE TITLE
problem with inspector

### ISSUE THREAD

**Issue by moperacz** [angular/batarang#57]
When I enable inspector, then `{ please select a scope }` appear in window but after clicking on something there is an error in the console 

>Uncaught TypeError: Cannot read property 'indexOf' of undefined

![Zrzut ekranu 2013-03-28 o 02 10 31](https://f.cloud.github.com/assets/585587/311499/a49a1e56-9744-11e2-80b2-4d7f53d1b255.png)

`Mac OS 10.8.3 / Chrome 26.0.1410.43`

If You need more info, than let me know

**Comment by SomeKittens** [comment]
Unable to reproduce.
