### ISSUE TITLE
Causes leaks with nested ng-repeat in nested scopes.

### ISSUE THREAD

**Issue by rasmusvhansen** [angular/batarang#62]
Nested ng-repeats updated by $timeout will leak memory (DOM objects) when plugin is enabled. I am having trouble reproducing with a minimal example. The issue might also involve nested controllers.
But in my project it is clear that when the plugin is enabled, it leaks. When it is disabled, the leak disappears.

If I get more time I will see if I can distill the essence of the issue in a Plnkr.

**Comment by SomeKittens** [comment]
Could not reproduce with latest version.  Thanks for the Plunker!
