### ISSUE TITLE
Batarang Models not showing scope | model editors

### ISSUE THREAD

**Issue by zeevl** [angular/batarang#70]
None of the angularjs sites I've visited will show the scope or model links in the Models pane of batarang.   For example, here's what I get from [todomvc](http://todomvc.com/architecture-examples/angularjs/#/):

![image](https://f.cloud.github.com/assets/1621969/588014/427a999e-c976-11e2-9779-2c19b306f8f0.png)

This prevents me from being able to edit any of the model data or do other cool things outlined in the screencast. 

Chrome version: 27.0.1453.93
OS: OS X v10.8.3
Betarang version: 0.4.2, although I've also tried grabbing the latest from github and loading that directly.

**Comment by SomeKittens** [comment]
This has been fixed in the new Scope rewrite.

**Comment by JenTechSystems** [comment]
I am experiencing this issue.

I go to Options > Show scopes and tick that

It correctly highlights the scoped elements on the page.

However, when I go to 'Models' tab, the Scopes list is empty and the root scope shows no Models i.e. it says "Select a scope to view its models"

I am using:

Chrome Version 47.0.2526.73 m
AngularJS Batarang (Stable) 0.4.3
Angular version: 1.4.9 implicit-superannuation

**Comment by SomeKittens** [comment]
@JenTechSystems the "Stable" version is not a part of this project, someone forked us a while ago and refuses to update.
