### ISSUE TITLE
breaks CSS live editing in Chrome dev tools

### ISSUE THREAD

**Issue by tkrugg** [angular/batarang#78]
It appears that when batarang is enabled I am sometimes unable to edit my CSS properties in the dev tools. This happens often after a few hours of work. When I try to change a of font-size or margin value, it goes back to it original value and doesn't show any change on the page.
Disabling the extension solves the problem. running version: 0.4.3

**Comment by SomeKittens** [comment]
Did a lot of CSS editing myself with Batarang enabled, was unable to reproduce (latest version).  If you manage to repro, I'll reopen.
