### ISSUE TITLE
Tab "Models" not working in Batarang 0.4.3

### ISSUE THREAD

**Issue by wajda** [angular/batarang#79]
Hi. I have installed Batarang form Google Web Store to different versions of Chrome on 3 different machines: Mac, Linux and WinXP. Unfortunately, the tab "Models" does NOT work acceptably on any of them :(

On WinXp I have Chrome 23.0.1271.95 and wasn't able to make Batarang to show scopes here at all. While on Mac and Linux I have always latest Chrome updates and it is working intermittently in about 40% of cases on them.
I wasn't able to figure out the conditions under which it is working on not, it just sometimes works sometimes doesn't with no obvious reasons.

No errors, nothing. It is enabled, it seems to highlight the app boundaries, binding and scopes when I tick the boxes under the "Options" tab. It also shows some date under the "AngularJS Properties" group in the Element view. BUT, It doesn't show scopes! Whatever I click on the "Models" nothing happens.

Is there any way to see Batarang error logs? Perhaps it could shed some lights. It seems like many people also have the same issue, but I wasn't able to find any explanation or workaround so far.

Thank you!

**Comment by gimzani** [comment]
Hey all - I had the same problem.

I did get it to work when it is coming through a server.  So, fire up node.js or IIS or Tomcat and serve it through a web server and it'll work.  

It no-likey file system.

**Comment by SomeKittens** [comment]
Should be fixed as of now.

**Comment by SomeKittens** [comment]
Whoops, wrong tab.  You'll need to explicitly allow Batarang access to `file://` urls: http://stackoverflow.com/a/17156345/1216976
