### ISSUE TITLE
Models are not updated correctly

### ISSUE THREAD

**Issue by tschoartschi** [angular/batarang#81]
Hey!

We are writing a bigger app with angular. Right now we have some problem with the batarang extension, because the model isn't updated correctly (or maybe we do something wrong). We faced this problem with some http.get calls and also with a simple drop down. Therefore we created a small fiddle: http://jsfiddle.net/tschoartschi/LSFZ6/2/

The idea behind the code is, to have a controller for a drop down and if the user changes his or her selection the value should be passed to the parent scope (a form controller). Therefore we created a $scope.$watch on the selected value. When passing it to the form controller, everything is updated correctly, only the values in the form controller stay the same and never change in the model tab in batarang.

The question is, are we doing something wrong or is this a bug? Can someone reproduce this issue? 

I'm on Win7 64bit, Chrome 29.0.1547.66 m and batarang 0.4.3, the following screenshot should illustrate the issue:

![update-dropdown](https://f.cloud.github.com/assets/1695329/1103757/c79b4f34-18c1-11e3-99a2-a5925278ea3b.jpg)

Thank you for helping!
All the best
Georg
PS: the issue with the http.get is documented in the google group: https://groups.google.com/forum/?hl=de#!topic/angular/_ursp_zuREg we don't have a fiddle for this right now, because it is harder to extract this code out of our entire codebase.

**Comment by SomeKittens** [comment]
Closed in above PR

**Comment by NikitaVr** [comment]
This Problem still occurs for me. Downloaded off of chrome web store, and when the state scope changes it does not update. It is bound to a form that is checked for validity. And even though the form goes from false to true, the change is not shown. Change only shows if i click off the element with the controller, and then click back onto it.

**Comment by mikiTestim** [comment]
+1
