### ISSUE TITLE
Add ability to disable partial cache while in dev tools

### ISSUE THREAD

**Issue by jca258** [angular/batarang#82]
It would be nice to have the option to disable cache while we are working with Batarang open as we can do with dev tools and browsers cache.

It would be faster to reload only the partial when we make changes on the code instead of loading everything again.

**Comment by SomeKittens** [comment]
I'm not sure what you mean - were you thinking of a hot reloader (changed components reload only that component instead of the whole page)?  If so, that's outside the scope of this project.
