### ISSUE TITLE
find controller name

### ISSUE THREAD

**Issue by linewx** [angular/batarang#83]
it would be very nice to get the controller name from the scope.

**Comment by SomeKittens** [comment]
Batarang now shows controller names in the scope tree.

**Comment by fonzarely** [comment]
Is there any way to show controllers names injected by ngRoute ? I only see the scope id of the controller.

**Comment by SomeKittens** [comment]
@fonzarely Sounds like a good candidate for a new issue - haven't tried that before.

**Comment by fonzarely** [comment]
Ok, i'll make one. thx

**Comment by g-patel** [comment]
I am on `angular@1.5.11` I don't see controller name in the Scope Tree, or on the Model panel on right side. Am I missing something?

![image](https://user-images.githubusercontent.com/12045773/43670620-93d97c7a-9742-11e8-91d1-c732127c4617.png)


@btford @SomeKittens any idea why I am not seeing controller name?
