### ISSUE TITLE
Batarang adds a hashbang to my apps

### ISSUE THREAD

**Issue by dariocravero** [angular/batarang#94]
Hi all,

For some particular reason, batarang (v0.4.3) seems to be adding a hashbang to all my apps.

I'm using Angular 1.2 > from RCs to the latest stable and the behaviour is the same.

Chrome v32.0.1700.41 beta.

Is anyone else experiencing this issue?
Cheers,
Darío

**Comment by SomeKittens** [comment]
Hashbang where?  In the URL?  Will reopen if we get a reproduction case.
