### ISSUE TITLE
Performance tab is making DevTools unresponsive

### ISSUE THREAD

**Issue by mzgol** [angular/batarang#97]
Profiling my Angular app via the Performance tab causes the whole DevTools to lag to the point of being unusable. This is on a mid-2012 non-retina MacBooks Pro with 16 GB of RAM and an SSD drive so a pretty fast machine, it may be even worse on less performant machines.

**Comment by SomeKittens** [comment]
Performance tab has been completely rebuilt, please open up a new issue if you have problems with the new one.
